# Archema RuboCop Configuration
#
# Layout/alignment settings come from tablecop.
# This file contains archema-specific settings.

plugins:
  - rubocop-minitest
  - rubocop-tablecop

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "coverage/**/*"
    - "examples/**/*"
    - "docs/msc/**/*"  # Experimental analysis scripts, not production code

# ─────────────────────────────────────────────────────────────────────────────
# Style
# ─────────────────────────────────────────────────────────────────────────────

# Allow both single and double quotes - use double by convention,
# single when semantically meaningful (e.g., JSON-style string keys)
Style/StringLiterals:
  Enabled: false

# Prefer explicit bracket syntax for symbol arrays
Style/SymbolArray:
  EnforcedStyle: brackets

# Prefer %w[] for word arrays
Style/WordArray:
  EnforcedStyle: percent

# Require class/module documentation (except for internal modules)
Style/Documentation:
  Enabled: true
  AllowedConstants:
    - ClassMethods  # Internal mixin modules don't need separate docs
    - DSL           # DSL namespace modules documented at parent level
  Exclude:
    - "lib/archema/schema/differ.rb"    # Operation classes are internal data structures
    - "lib/archema/shared_types.rb"     # Module reopening, documented in main file
    - "lib/archema/stores.rb"           # Module reopening, documented in main file
    - "test/**/*"                       # Test classes don't need documentation

# Allow multi-line block chains when readable
Style/MultilineBlockChain:
  Enabled: false

# DANGEROUS: Autocorrect converts !!value to !value.nil? which has
# different semantics for boolean values (!!false → false, !false.nil? → true)
Style/DoubleNegation:
  Enabled: false

# DANGEROUS: Changes semantics with mixed key types.
# reject { |k, _| keys.include?(k) } handles symbol/string keys correctly,
# but hash.except(*keys) treats :key and "key" as different.
Style/HashExcept:
  Enabled: false

# DANGEROUS: Converts `Module % [args]` to `format(Module, args)` which breaks
# custom % methods (like ANSI % ["text", :style] for nested color spans).
Style/FormatString:
  Enabled: false

# ─────────────────────────────────────────────────────────────────────────────
# Layout
# ─────────────────────────────────────────────────────────────────────────────

Layout/LineLength:
  Max: 140

# Allow RBS inline type comments like #: Type
Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

# ─────────────────────────────────────────────────────────────────────────────
# Naming
# ─────────────────────────────────────────────────────────────────────────────

# DISABLED: Renames @data_layer_instance to @data_layer, but tests
# use instance_variable_set(:@data_layer_instance, nil) to reset state.
Naming/MemoizedInstanceVariableName:
  Enabled: false

# DISABLED: Too pedantic about underscores in numbers (last_5, chain_from_11, 1_0_0)
Naming/VariableNumber:
  Enabled: false

# Allow common short parameter names
Naming/MethodParameterName:
  AllowedNames:
    - a
    - b
    - c
    - e   # exception, element, entry
    - i   # index
    - j   # secondary index
    - k   # key
    - v   # value
    - h   # hash
    - n   # number, count
    - x   # coordinate, generic
    - y   # coordinate
    - id  # identifier
    - io  # IO object
    - op  # operation
    - db  # database
    - fn  # function
    - s1  # string comparison (levenshtein)
    - s2  # string comparison (levenshtein)
    - sc  # sub_constraint in composition constraints
    - ds  # dataset (Sequel)
    - to  # destination (from:, to:)
    - of  # element type (array of:)
    - _   # explicitly unused

# Allow has_* prefix for methods that genuinely "have" something (not just predicates)
# has_default?, has_role?, etc. are clearer than default?, role? in context
Naming/PredicatePrefix:
  AllowedMethods:
    - has_default?
    - has_role?
    - has_managed_data?
    - has_cardinality_constraints?
    - has_temporal_defaults?
    - has_irreversible_operations?
    - has_one       # DSL method: has_one :profile, Profile
    - has_many      # DSL method: has_many :posts, Post

# ─────────────────────────────────────────────────────────────────────────────
# Lint
# ─────────────────────────────────────────────────────────────────────────────

Lint/UselessAssignment:
  Enabled: true

# DISABLED: Forces combining case branches that happen to have the same result,
# but often they represent distinct semantic intents. With tablecop alignment,
# separate branches read as visual lookup tables which is clearer.
Lint/DuplicateBranch:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Lint/MissingSuper:
  Enabled: false

# DANGEROUS: Removes `require "set"` as "redundant" in Ruby 3.2+, but code
# using Set.new will fail if Set isn't explicitly required.
Lint/RedundantRequireStatement:
  Enabled: false

# ─────────────────────────────────────────────────────────────────────────────
# Metrics - Lenient thresholds for real-world code
# ─────────────────────────────────────────────────────────────────────────────

Metrics/MethodLength:
  Max: 40
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - "lib/chiridion/engine/inline_rbs_loader.rb"

Metrics/AbcSize:
  Max: 50
  Exclude:
    - "lib/chiridion/engine/inline_rbs_loader.rb"

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - "lib/chiridion/engine/inline_rbs_loader.rb"

Metrics/ClassLength:
  Max: 300
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/BlockLength:
  Max: 40
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - "test/**/*"
    - "spec/**/*"
    - "features/**/*"
    - "lib/chiridion/engine/inline_rbs_loader.rb"
  AllowedMethods:
    - describe
    - context
    - define
    - configure
    - namespace

Metrics/ParameterLists:
  Max: 15

# ─────────────────────────────────────────────────────────────────────────────
# Minitest
# ─────────────────────────────────────────────────────────────────────────────

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 8

# DANGEROUS: Converts `assert obj.foo?` to `assert_predicate obj, :foo?`
# which breaks refinements since assert_predicate uses send() internally
# and refinements are lexically scoped (don't work with send).
Minitest/AssertPredicate:
  Enabled: false

Minitest/RefutePredicate:
  Enabled: false
