# Devex RuboCop Configuration
#
# Inherits from the shared rubocop-dx.yml base config.
# This file contains devex-specific overrides only.

inherit_from: config/rubocop-dx.yml

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "coverage/**/*"
    - "examples/**/*"
    - "config/**/*"     # YAML config files, not Ruby
    - "docs/msc/**/*"   # Experimental analysis scripts, not production code

# ─────────────────────────────────────────────────────────────────────────────
# Project-specific overrides
# ─────────────────────────────────────────────────────────────────────────────

# Require class/module documentation (except for internal modules)
Style/Documentation:
  Enabled: true
  AllowedConstants:
    - ClassMethods  # Internal mixin modules don't need separate docs
    - DSL           # DSL namespace modules documented at parent level
  Exclude:
    - "test/**/*"   # Test classes don't need documentation
